### ISSUE TITLE
Error with Matab R2018B

### ISSUE THREAD

**Issue by Chaitanya-Patel** [rodyo/FEX-PhysicalQuantity#1]
Hi

I am getting following error while using the given examples.

`L = Length();`
Error using Length
The specified superclass 'PhysicalQuantityInterface' contains a parse error, cannot be found on MATLAB's search path,
or is shadowed by another file with the same name.

**Comment by Chaitanya-Patel** [comment]
Hi

Sorry for above issue. I could resolve it by adding subfolders in matlab path.

**Comment by rodyo** [comment]
Regardless: thanks for pointing it out 😊 
closing with no action
